### ISSUE TITLE
Exception thrown when changing experiments on same controller process.

### ISSUE THREAD

**Issue by gnramos** [matheusportela/Multiagent-RL#57]
Assuming a controller is running ($ python2 controller.py), this is reproducible by running the following tests (in this order):

$ python2 simulator.py -l 1 -t 1 -e 4 > simluator_e4.log
$ python2 simulator.py -l 1 -t 1 -e 5 > simluator_e5.log

Log files attached. Probably due to layout changes between experiments 4 & 5. Relaunching the controller and running experiment 5 (as indicated before) works fine. 

[log.zip](https://github.com/matheusportela/Multiagent-RL/files/293896/log.zip)

**Comment by matheusportela** [comment]
Since we now use `simulation.py` to launch experiments, this is no longer an issue (unless we decide to enable long running controllers and experiments hot swap).
