### ISSUE TITLE
undergraduate thesis

### ISSUE THREAD

**Issue by TzuRen** [matheusportela/Multiagent-RL#92]
Please upload "Behavior selection for multiple autonomous agents with reinforcement learning in stochastic environments"?!

**Comment by matheusportela** [comment]
Hi. I just updated the links for the undergraduate thesis. Please notice it is written in Portuguese.
I can refer to the conference paper in English: http://www.sbgames.org/sbgames2015/anaispdf/computacao-short/147936.pdf. I presents the same algorithm but lacks the experimental results.
